import os

# Publicly accessible twitter maven repo that houses twitter-commons artifacts
repo(name = 'public',
     url = 'http://maven.twttr.com',
     push_db = os.path.join(os.path.dirname(__file__), 'pushdb', 'publish.properties'))

