# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Test that an empty junit_tests target can still be consumed by junit_run
junit_tests(name='empty',
  sources=globs('this_matches_nothing'),
)
